#!/bin/bash

Spot(){

if ps -C spotify > /dev/null; then
    PLAYER="spotify"
elif ps -C spotifyd > /dev/null; then
    PLAYER="spotifyd"
elif pgrep firefox > /dev/null; then
    PLAYER="firefox"
elif pgrep telegram-deskto > /dev/null; then
    PLAYER="telegram"
fi

   

    if [ "$PLAYER" = "firefox" ] || [ "$PLAYER" = "telegram" ] || [ "$PLAYER" = "spotify" ] || [ "$PLAYER" = "spotifyd" ]; then
        ARTIST=$(playerctl metadata artist)
        TRACK=$(playerctl metadata title)
        STATUS=$(playerctl -p spotify status)
        FIREFOX=$(playerctl -p firefox status)
        TELE=$(playerctl -p tdesktop status)
        SHUFFLE=$(playerctl shuffle)
                
            if [[ $STATUS = Playing ]]; then
                STATUS="Icons/Candy/pause.svg"
            elif [[ $STATUS = Paused ]]; then
                STATUS="Icons/Candy/play.svg"
            elif [[ $FIREFOX = Playing ]]; then
                STATUS="Icons/Candy/pause.svg"
            elif [[ $FIREFOX = Paused ]]; then
                STATUS="Icons/Candy/play.svg"
            elif [[ $TELE = Playing ]]; then
                STATUS="Icons/Candy/pause.svg"
            elif [[ $TELE = Paused ]]; then
                STATUS="Icons/Candy/play.svg" 
            fi
            
        if [[ "$PLAYER" = "spotify" ]]; then
          printf "$STATUS"
        elif [[ "$PLAYER" != "spotify" ]]; then
            printf "$STATUS"
        fi
    fi

}

Get_Art()
{

tmp_dir="/tmp/spotify"
tmp_cover_path=$tmp_dir/cover.png

if [ ! -d $tmp_dir ]; then
	mkdir -p $tmp_dir
fi

artlink="$(playerctl metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"

if [ $(playerctl metadata mpris:artUrl) ]; then
	curl -s "$artlink" --output $tmp_cover_path;
else 
    cp ~/.config/eww/Icons/Panel/music-hover.svg $tmp_cover_path;
fi

}

Status()
{
    if ps -C spotify > /dev/null; then
        echo "Spotify  playing"
    elif ps -C firefox > /dev/null; then
        echo "Firefox  playing"
    elif pgrep telegram-deskto > /dev/null; then
        echo "Telegram Now"
    else
        echo "No       playing"
    fi

}


case $1 in 
	SPOT) Spot 	;;
    PLAYING) Status     ;;
esac

Get_Art